### ISSUE TITLE
Add WP readme.txt file

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-multiple-forum-post#1]
Here's the format from wordpress.org: https://wordpress.org/plugins/about/readme.txt

**Comment by rjbaniel** [comment]
How's this? https://github.com/cuny-academic-commons/bp-multiple-forum-post/commit/71f34b4b6181e0ba1488457bf8aecbcbaef36ed2

**Comment by boonebgorges** [comment]
Yeah, this looks great. Thanks!
