### ISSUE TITLE
Activity actions use activity content rather than topic title

### ISSUE THREAD

**Issue by modelm** [cuny-academic-commons/bp-multiple-forum-post#11]
Hi @boonebgorges !

I noticed that after `bpmfp_add_duplicate_topics_to_activity_action_string` runs, `bbp_create_topic` activities in the feed display the activity content for the action, rather than the title. I found that this line is responsible:

https://github.com/cuny-academic-commons/bp-multiple-forum-post/blob/master/includes/activity-feed.php#L65

`$topic_title = $displayed_activity->content;`

I believe this should be changed to:

`$topic_title = bbp_get_topic_title( $displayed_activity->secondary_item_id );`

This way the value of the action is unchanged after this filter runs other than to add the list of forums to the end.

**Comment by boonebgorges** [comment]
Yup, this is definitely a bug. Thank you for the pr!
