### ISSUE TITLE
Implement nonce checks

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-multiple-forum-post#5]
WP nonce checks help prevent against CSRF attacks, and should be used before perfoming any action that modifies content in the database. 

A nonce check should be included in the form submission process of this plugin.

See http://codex.wordpress.org/WordPress_Nonces for a primer.

**Comment by rjbaniel** [comment]
Addressed here: https://github.com/cuny-academic-commons/bp-multiple-forum-post/commit/6eed651cb764f534f525cd1e3f5a8e417ea23e37

**Comment by boonebgorges** [comment]
Looks good!
