### ISSUE TITLE
User permission checks

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-multiple-forum-post#6]
Currently, the plugin checks `$_POST['groups-to-post-to']` and cross-posts in each of these groups, without checking that the user does in fact have permission to post in these places. This means it'd be possible to modify the POST payload to post to groups where you shouldn't be able to post. We need some sort of permission check. `groups_is_user_member()` is probably good enough.

**Comment by rjbaniel** [comment]
Addressed here: https://github.com/cuny-academic-commons/bp-multiple-forum-post/commit/6eed651cb764f534f525cd1e3f5a8e417ea23e37

**Comment by boonebgorges** [comment]
Cool!
