### ISSUE TITLE
Checkbox labels should be properly associated with inputs

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/bp-multiple-forum-post#7]
Checkboxes have `<label>` elements, but their `for` attributes don't point to anything. `label:for` should correspond to `input:id`, which means you need to do something like `<input type="checkbox" ... id="group-<?php echo $group->id; ?>" ... >`

**Comment by rjbaniel** [comment]
Addressed here: https://github.com/cuny-academic-commons/bp-multiple-forum-post/commit/6eed651cb764f534f525cd1e3f5a8e417ea23e37

**Comment by boonebgorges** [comment]
Looks good.
